In [3]:
import pandas as pd

In [4]:
equity_tickers = pd.read_csv("../dataset/equity_tickers.csv")

In [5]:
equity_tickers

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE
0,20MICRONS,20 Microns Limited,EQ,06-OCT-2008,5.0,1,INE144J01027,5
1,21STCENMGM,21st Century Management Services Limited,EQ,03-MAY-1995,10.0,1,INE253B01015,10
2,360ONE,360 ONE WAM LIMITED,EQ,19-SEP-2019,1.0,1,INE466L01038,1
3,3IINFOLTD,3i Infotech Limited,EQ,22-OCT-2021,10.0,1,INE748C01038,10
4,3MINDIA,3M India Limited,EQ,13-AUG-2004,10.0,1,INE470A01017,10
...,...,...,...,...,...,...,...,...
2245,ZOTA,Zota Health Care LImited,EQ,19-AUG-2019,10.0,1,INE358U01012,10
2246,ZUARI,Zuari Agro Chemicals Limited,EQ,27-NOV-2012,10.0,1,INE840M01016,10
2247,ZUARIIND,ZUARI INDUSTRIES LIMITED,EQ,12-APR-1995,10.0,1,INE217A01012,10
2248,ZYDUSLIFE,Zydus Lifesciences Limited,EQ,18-APR-2000,1.0,1,INE010B01027,1
2249,ZYDUSWELL,Zydus Wellness Limited,EQ,13-NOV-2009,2.0,1,INE768C01028,2

In [6]:
equity_tickers['SYMBOL']

0        20MICRONS
1       21STCENMGM
2           360ONE
3        3IINFOLTD
4          3MINDIA
           ...
2245          ZOTA
2246         ZUARI
2247      ZUARIIND
2248     ZYDUSLIFE
2249     ZYDUSWELL
Name: SYMBOL, Length: 2250, dtype: object

In [ ]:
equity_tickers[" ISIN NUMzBER"]

0       INE144J01027
1       INE253B01015
2       INE466L01038
3       INE748C01038
4       INE470A01017
            ...
2245    INE358U01012
2246    INE840M01016
2247    INE217A01012
2248    INE010B01027
2249    INE768C01028
Name:  ISIN NUMBER, Length: 2250, dtype: object

In [15]:
equity_tickers["INSTRUMENT_KEY"] = "NSE_EQ|" + equity_tickers["SYMBOL"]

In [16]:
equity_tickers

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE,INSTRUMENT_KEY
0,20MICRONS,20 Microns Limited,EQ,06-OCT-2008,5.0,1,INE144J01027,5,NSE_EQ|20MICRONS
1,21STCENMGM,21st Century Management Services Limited,EQ,03-MAY-1995,10.0,1,INE253B01015,10,NSE_EQ|21STCENMGM
2,360ONE,360 ONE WAM LIMITED,EQ,19-SEP-2019,1.0,1,INE466L01038,1,NSE_EQ|360ONE
3,3IINFOLTD,3i Infotech Limited,EQ,22-OCT-2021,10.0,1,INE748C01038,10,NSE_EQ|3IINFOLTD
4,3MINDIA,3M India Limited,EQ,13-AUG-2004,10.0,1,INE470A01017,10,NSE_EQ|3MINDIA
...,...,...,...,...,...,...,...,...,...
2245,ZOTA,Zota Health Care LImited,EQ,19-AUG-2019,10.0,1,INE358U01012,10,NSE_EQ|ZOTA
2246,ZUARI,Zuari Agro Chemicals Limited,EQ,27-NOV-2012,10.0,1,INE840M01016,10,NSE_EQ|ZUARI
2247,ZUARIIND,ZUARI INDUSTRIES LIMITED,EQ,12-APR-1995,10.0,1,INE217A01012,10,NSE_EQ|ZUARIIND
2248,ZYDUSLIFE,Zydus Lifesciences Limited,EQ,18-APR-2000,1.0,1,INE010B01027,1,NSE_EQ|ZYDUSLIFE
2249,ZYDUSWELL,Zydus Wellness Limited,EQ,13-NOV-2009,2.0,1,INE768C01028,2,NSE_EQ|ZYDUSWELL

In [ ]:
instrument = "NSE_EQ|INE009A01021"
date = "2025-03-20"
access_token = ""

In [ ]:
from tqdm import tqdm
import pandas as pd
import requests
import time

equity_tickers = pd.read_csv("../dataset/equity_tickers.csv")
equity_tickers["INSTRUMENT_KEY"] = "NSE_EQ|" + equity_tickers[" ISIN NUMBER"]

date = "2025-03-20"
access_token = ""

headers = {
    "Authorization": f"Bearer {access_token}"
}

base_url = "https://api.upstox.com/v2/historical-candle"

all_prices = []

# 👇 tqdm added here
for instrument in tqdm(equity_tickers["INSTRUMENT_KEY"], desc="Fetching data"):

    try:
        url = f"{base_url}/{instrument}/1minute/{date}/{date}"
        response = requests.get(url, headers=headers)

        data = response.json()

        if "data" not in data or "candles" not in data["data"]:
            all_prices.append([])
            continue

        candles = data["data"]["candles"]
        close_prices = [c[4] for c in candles]

        all_prices.append(close_prices)

        time.sleep(0.2)

    except Exception as e:
        print(f"Error with {instrument}: {e}")
        all_prices.append([])